source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RxOptional Examples' do
  pod 'RxOptional', :path => '../'
  pod 'RxSwift', :git => 'https://github.com/ReactiveX/RxSwift', :branch => 'swift-3.0'
  pod 'RxCocoa', :git => 'https://github.com/ReactiveX/RxSwift', :branch => 'swift-3.0'
end

target 'RxOptional Tests' do
  pod 'RxOptional', :path => '../'
  pod 'RxSwift', :git => 'https://github.com/ReactiveX/RxSwift', :branch => 'swift-3.0'
  pod 'RxCocoa', :git => 'https://github.com/ReactiveX/RxSwift', :branch => 'swift-3.0'

  pod 'Quick'
  pod 'Nimble'
end
